# for building images add following variable as described here
# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html#building-a-docker-image-with-kaniko
# name: KANIKO_CONFIG_JSON
# value:
#   { "auths":
#     { "registry_url":
#       { "auth":"base64_encoded_username_and_password" }
#     }
#   }
#
# the following values above need to be replaced.
# registry_url = "https://index.docker.io/v1/" for default docker registry or $CI_REGISTRY
# base64_encoded_username_and_password = "username:password" base64 encoded
stages:
  - containerisation

containerise-frontend:
  stage: "containerisation"
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  needs: [ "build_frontend", "test_frontend" ]
  rules:
    - if: '$CI_COMMIT_TAG != null'
  before_script:
    - echo "$KANIKO_CONFIG_JSON" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "docker.io/cloudseeker/frontend:$CI_COMMIT_TAG"
      --destination "docker.io/cloudseeker/frontend:latest"

containerise-backend:
  stage: "containerisation"
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  needs: [ "build_backend", "test_backend" ]
  rules:
    - if: '$CI_COMMIT_TAG != null'
  before_script:
    - echo "$KANIKO_CONFIG_JSON" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "docker.io/cloudseeker/backend:$CI_COMMIT_TAG"
      --destination "docker.io/cloudseeker/backend:latest"

containerise-reverseproxy:
  stage: "containerisation"
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  needs: [ ]
  rules:
    - if: '$CI_COMMIT_TAG != null'
  before_script:
    - echo "$KANIKO_CONFIG_JSON" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/reverseproxy"
      --dockerfile "${CI_PROJECT_DIR}/reverseproxy/Dockerfile"
      --destination "docker.io/cloudseeker/reverseproxy:$CI_COMMIT_TAG"
      --destination "docker.io/cloudseeker/reverseproxy:latest"
