image: node:18.16.0

stages:
  - build
  - test

# This folder is cached between builds
cache:
  paths:
    - backend/node_modules/

test_backend:
  stage: test
  needs: []
  before_script:
    - cd backend
    - npm install
  script:
    - npm test
  artifacts:
    when: on_success
    paths:
      - backend/build/
    reports:
      junit: build/tests/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: build/coverage/cobertura-coverage.xml

build_backend:
  stage: build
  needs: []
  before_script:
    - cd backend
    - npm install
  script:
    - npm run build
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - backend/build/

formatting_backend:
  stage: test
  needs: []
  before_script:
    - cd backend
    - npm install
  script:
    - npm run checkformat

