image: node:latest

stages:
  - test
  
cache:
  paths:
    - backend/node_modules/

test_backend: # job
  stage: test
  before_script:
    - cd backend
    - npm install # building
  script:
    - npm test # testing
  artifacts:
    paths:
      - junit.xml
    reports:
      junit: junit.xml
    expire_in: never
