image: node:latest

stages:
  - test
  
cache:
  paths:
    - frontend/node_modules/

test_frontend: # job
  stage: test
  before_script:
    - cd frontend
    - npm install # building
  script:
    - npm run test-ci # testing