image: atlassianlabs/docker-node-jdk-chrome-firefox:latest

stages:
  - build
  - test
  
cache:
  paths:
    - frontend/node_modules/

test_frontend: # job
  stage: test
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run test-ci # testing

build_frontend: # job
  stage: build
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run build # building
  artifacts:
    paths:
      - "frontend/dist/**"
    expire_in: never